spring:
  profiles:
    include: migration

  jpa:
    legacy-ad:
      hikari:
        maximun-pool-size: 100

    recent-ad:
      hikari:
        maximun-pool-size: 100

  cloud:
    stream:
      binders:
        legacy-rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: admin
                password: 1234
                virtual-host: legacy

      bindings:
        legacyConsumer-in-0:
          binder: legacy-rabbit
          destination: legacy-topic
          group: migration

server:
  port: 8081

logging:
  file:
    name: logs/gradual.log