spring:
  jpa:
    legacy-ad:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3306/legacy-ad
        username: root
        password: 1234
        maximum-pool-size: 800

      properties:
        hibernate:
          show_sql: true
          hbm2ddl.auto: update
          physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  cloud:
    stream:
      binders:
        legacy-rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: admin
                password: 1234
                virtual-host: legacy

      bindings:
        legacy-rabbit-out:
          binder: legacy-rabbit
          destination: legacy-topic