version: "3.8"

services:
  mysql-server:
    image: mysql
    volumes:
      - ./data/legacy-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=legacy-ad
    ports:
      - "3306:3306"

  postgresql-server:
    image: postgres
    volumes:
      - ./data/recent-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"

  rabbitmq-server:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=1234
      - RABBITMQ_DEFAULT_VHOST=legacy
